# Generated by Django 6.0.4 on 2026-04-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador'), ('executive', 'Ejecutivo C-Suite'), ('division_manager', 'Director de División'), ('tech_manager', 'Gerente de Tecnología'), ('security_analyst', 'Analista de Seguridad'), ('finops_analyst', 'Analista FinOps'), ('pmo_manager', 'Gerente PMO'), ('hr_manager', 'Gerente de RRHH')], default='usuario', help_text='Rol del usuario en el sistema', max_length=20),
        ),
    ]
