# Generated by Django 6.0.3 on 2026-04-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto visible en el menú', max_length=100)),
                ('url_name', models.CharField(help_text='Nombre de URL con namespace, por ejemplo ventures:home', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar en el menú')),
                ('open_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nav Item',
                'verbose_name_plural': 'Nav Items',
                'ordering': ['order'],
            },
        ),
    ]
