# Generated by Django 6.0.5 on 2026-05-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0002_seed_navitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(help_text='ID único del satélite', max_length=50, unique=True)),
                ('satellite_name', models.CharField(help_text='Nombre del satélite', max_length=200)),
                ('norad_catalog_id', models.CharField(blank=True, help_text='NORAD Catalog Number', max_length=50)),
                ('status', models.CharField(choices=[('operational', 'Operacional'), ('testing', 'En Pruebas'), ('maintenance', 'Mantenimiento'), ('dormant', 'Dormido'), ('decommissioned', 'Fuera de Servicio')], default='operational', max_length=30)),
                ('altitude_km', models.FloatField(help_text='Altitud en kilómetros')),
                ('orbital_velocity_km_s', models.FloatField(help_text='Velocidad orbital en km/s')),
                ('inclination_degrees', models.FloatField(help_text='Inclinación orbital en grados')),
                ('orbital_period_minutes', models.FloatField(help_text='Período orbital en minutos')),
                ('apogee_km', models.FloatField(blank=True, help_text='Apogeo en km', null=True)),
                ('perigee_km', models.FloatField(blank=True, help_text='Perigeo en km', null=True)),
                ('mass_kg', models.FloatField(help_text='Masa en kilogramos')),
                ('power_generation_watts', models.FloatField(help_text='Generación de energía en watts')),
                ('design_lifespan_years', models.IntegerField(blank=True, null=True)),
                ('launch_date', models.DateField(help_text='Fecha de lanzamiento')),
                ('operator', models.CharField(help_text='Operador del satélite', max_length=200)),
                ('launch_site', models.CharField(blank=True, help_text='Sitio de lanzamiento', max_length=200)),
                ('frequency_ghz', models.FloatField(blank=True, help_text='Frecuencia en GHz', null=True)),
                ('coverage_area_km2', models.FloatField(blank=True, help_text='Área de cobertura en km²', null=True)),
                ('mission_type', models.CharField(help_text='Tipo de misión (Earth Observation, Communications, etc)', max_length=100)),
                ('primary_payload', models.CharField(blank=True, help_text='Carga útil principal', max_length=200)),
                ('last_telemetry_update', models.DateTimeField(blank=True, null=True)),
                ('signal_strength_percent', models.FloatField(default=100, help_text='Intensidad de señal %')),
                ('battery_health_percent', models.FloatField(default=100, help_text='Salud de batería %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etl_source', models.CharField(blank=True, help_text='Fuente ETL', max_length=100)),
            ],
            options={
                'verbose_name': 'Satellite',
                'verbose_name_plural': 'Satellites',
                'ordering': ['-launch_date'],
                'indexes': [models.Index(fields=['status'], name='ventures_sa_status_edf039_idx'), models.Index(fields=['launch_date'], name='ventures_sa_launch__66ccd9_idx')],
            },
        ),
    ]
