# Generated by Django 6.0.5 on 2026-05-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0003_satellite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(help_text='ID único del registro de error', max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(help_text='Fecha y hora del evento')),
                ('satellite_id', models.CharField(help_text='ID del satélite', max_length=50)),
                ('satellite_name', models.CharField(help_text='Nombre del satélite', max_length=200)),
                ('orbit_type', models.CharField(choices=[('LEO', 'LEO - Órbita Baja'), ('MEO', 'MEO - Órbita Media'), ('GEO', 'GEO - Órbita Geoestacionaria'), ('HEO', 'HEO - Órbita Elíptica Alta')], help_text='Tipo de órbita', max_length=20)),
                ('satellite_type', models.CharField(choices=[('IoT', 'IoT'), ('Relay', 'Relay'), ('Observación', 'Observación'), ('Seguridad', 'Seguridad'), ('Datos', 'Datos'), ('Investigación', 'Investigación'), ('Navegación', 'Navegación')], help_text='Tipo de satélite', max_length=50)),
                ('ground_station', models.CharField(help_text='Estación terrena', max_length=100)),
                ('operator_id', models.CharField(blank=True, help_text='ID del operador', max_length=100)),
                ('error_code', models.CharField(help_text='Código de error (ej: ERR-RX-004)', max_length=20)),
                ('error_description', models.CharField(help_text='Descripción del error', max_length=500)),
                ('subsystem', models.CharField(help_text='Subsistema afectado (Receptor, Transmisor, OBC, ADCS, etc)', max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], help_text='Nivel de severidad', max_length=20)),
                ('link_type', models.CharField(help_text='Tipo de enlace (Ka-Band, X-Band, etc)', max_length=100)),
                ('protocol', models.CharField(help_text='Protocolo utilizado', max_length=100)),
                ('frequency_mhz', models.FloatField(help_text='Frecuencia en MHz')),
                ('snr_db', models.FloatField(help_text='Relación Señal/Ruido en dB')),
                ('bit_error_rate', models.CharField(help_text='Tasa de error de bits', max_length=50)),
                ('elevation_angle_deg', models.FloatField(help_text='Ángulo de elevación en grados')),
                ('event_duration_ms', models.BigIntegerField(help_text='Duración del evento en ms')),
                ('retry_count', models.IntegerField(help_text='Número de reintentos')),
                ('weather_condition', models.CharField(choices=[('Clear', 'Despejado'), ('Cloudy', 'Nublado'), ('Fog', 'Niebla'), ('Rain', 'Lluvia'), ('Snow', 'Nieve'), ('Stormy', 'Tormentoso')], help_text='Condición meteorológica', max_length=100)),
                ('requires_action', models.BooleanField(default=False, help_text='¿Requiere acción?')),
                ('resolved', models.BooleanField(default=False, help_text='¿Ha sido resuelto?')),
                ('resolution_action', models.CharField(blank=True, help_text='Acción de resolución tomada', max_length=500)),
                ('resolution_time_min', models.IntegerField(blank=True, help_text='Tiempo de resolución en minutos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Satellite Error Log',
                'verbose_name_plural': 'Satellite Error Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='satellite',
            name='ventures_sa_status_edf039_idx',
        ),
        migrations.RemoveIndex(
            model_name='satellite',
            name='ventures_sa_launch__66ccd9_idx',
        ),
        migrations.DeleteModel(
            name='Satellite',
        ),
        migrations.AddIndex(
            model_name='satelliteerrorlog',
            index=models.Index(fields=['satellite_id'], name='ventures_sa_satelli_96da63_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteerrorlog',
            index=models.Index(fields=['timestamp'], name='ventures_sa_timesta_fcedd6_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteerrorlog',
            index=models.Index(fields=['severity'], name='ventures_sa_severit_af5407_idx'),
        ),
    ]
