# Generated by Django 6.0.2 on 2026-03-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('costos', 'Ahorro de Costos'), ('productividad', 'Productividad'), ('resiliencia', 'Resiliencia Operativa'), ('agilidad', 'Agilidad Empresarial'), ('innovacion', 'Innovación'), ('sostenibilidad', 'Sostenibilidad')], max_length=20)),
                ('metric_name', models.CharField(max_length=120, verbose_name='Nombre de la Métrica')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('target', models.CharField(max_length=80, verbose_name='Meta')),
                ('current', models.CharField(blank=True, max_length=80, verbose_name='Valor Actual')),
                ('progress', models.IntegerField(default=0, help_text='0-100', verbose_name='Progreso (%)')),
                ('trend_up', models.BooleanField(default=True, verbose_name='Tendencia positiva')),
            ],
            options={
                'verbose_name': 'KPI Cloud',
                'verbose_name_plural': 'KPIs Cloud',
                'ordering': ['pillar', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('focus', models.CharField(max_length=200, verbose_name='Enfoque')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('cloud_relevance', models.TextField(verbose_name='Relevancia para la Nube')),
                ('cloud_priority', models.CharField(choices=[('alta', 'Alta — Lanzamiento Inmediato'), ('media', 'Media — Migración Planificada'), ('baja', 'Baja — Evaluación en Curso')], default='media', max_length=10)),
                ('icon', models.CharField(default='◈', max_length=10, verbose_name='Ícono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='divisions/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'División de Negocio',
                'verbose_name_plural': 'Divisiones de Negocio',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80, verbose_name='Rol / Cargo')),
                ('full_title', models.CharField(max_length=120, verbose_name='Título Completo')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('level', models.CharField(choices=[('CEO', 'CEO — Dirección Suprema'), ('C_LEVEL', 'C-Level — Alta Dirección'), ('VP', 'VP / Director General')], default='C_LEVEL', max_length=10)),
                ('strategic_responsibilities', models.TextField(verbose_name='Responsabilidades Estratégicas')),
                ('cloud_role', models.TextField(verbose_name='Rol en la Transformación Cloud')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ejecutivo C-Level',
                'verbose_name_plural': 'Equipo Ejecutivo',
                'ordering': ['order', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('classification', models.CharField(choices=[('vehiculo', 'Vehículo'), ('traje', 'Traje / Armadura'), ('arma', 'Arma No Letal'), ('vigilancia', 'Vigilancia'), ('comunicacion', 'Comunicación / IA'), ('medico', 'Equipo Médico')], max_length=30)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('specs', models.TextField(blank=True, verbose_name='Especificaciones')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('desarrollo', 'En Desarrollo'), ('retirado', 'Retirado'), ('clasificado', 'Clasificado')], default='activo', max_length=20)),
                ('year_developed', models.IntegerField(verbose_name='Año de Desarrollo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gadgets/')),
                ('threat_neutralized', models.IntegerField(default=0, verbose_name='Incidentes Resueltos')),
                ('clearance_level', models.CharField(default='OMEGA', max_length=20)),
            ],
            options={
                'verbose_name': 'Gadget / Tecnología',
                'verbose_name_plural': 'Gadgets / Tecnologías',
                'ordering': ['classification', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre Real')),
                ('alias', models.CharField(max_length=120, verbose_name='Alias')),
                ('threat_level', models.CharField(choices=[('S', 'S — Catastrófico'), ('A', 'A — Crítico'), ('B', 'B — Elevado'), ('C', 'C — Moderado')], max_length=2)),
                ('status', models.CharField(choices=[('detenido', 'Detenido — Arkham'), ('en_libertad', 'En Libertad'), ('neutralizado', 'Neutralizado'), ('desaparecido', 'Paradero Desconocido')], max_length=20)),
                ('crimes', models.TextField(verbose_name='Crímenes Documentados')),
                ('description', models.TextField(verbose_name='Perfil')),
                ('times_detained', models.IntegerField(default=0, verbose_name='Veces Detenido')),
                ('last_detained', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='villains/')),
                ('arkham_cell', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Villano / Amenaza',
                'verbose_name_plural': 'Registro de Amenazas',
                'ordering': ['threat_level', 'alias'],
            },
        ),
    ]
