# Generated by Django 6.0.4 on 2026-05-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberSecurityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=100)),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('affected_system', models.CharField(max_length=200)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
