# Generated by Django 6.0.4 on 2026-05-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybersecurityrecord',
            name='status',
            field=models.CharField(default='PENDIENTE', max_length=100),
            preserve_default=False,
        ),
    ]
