# Generated by Django 6.0.4 on 2026-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('adj_close', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('market_cap_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('exchange', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-date', 'ticker'],
            },
        ),
    ]
