# Generated by Django 6.0.4 on 2026-04-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=100, unique=True)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('uei_number', models.CharField(blank=True, max_length=50)),
                ('cage_code', models.CharField(blank=True, max_length=20)),
                ('fpds_transaction_id', models.CharField(blank=True, max_length=100)),
                ('agency', models.CharField(max_length=200)),
                ('contractor_name', models.CharField(blank=True, max_length=200)),
                ('obligated_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('contract_ceiling_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('modification_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('etl_source_system', models.CharField(blank=True, max_length=100)),
                ('xml_schema_version', models.CharField(blank=True, max_length=50)),
                ('data_feed_format', models.CharField(blank=True, max_length=100)),
                ('security_classification', models.CharField(blank=True, max_length=100)),
                ('naics_code', models.CharField(blank=True, max_length=20)),
                ('naics_description', models.CharField(blank=True, max_length=200)),
                ('psc_code', models.CharField(blank=True, max_length=20)),
                ('cyber_compliance_level', models.CharField(blank=True, max_length=100)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('performance_status', models.CharField(blank=True, max_length=100)),
                ('small_business', models.BooleanField(default=False)),
                ('veteran_owned', models.BooleanField(default=False)),
                ('women_owned', models.BooleanField(default=False)),
                ('hubzone', models.BooleanField(default=False)),
                ('place_of_performance_state', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Defense Contract',
                'verbose_name_plural': 'Defense Contracts',
                'ordering': ['-obligated_amount_usd'],
            },
        ),
    ]
