# Generated by Django 6.0.4 on 2026-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=150)),
                ('nivel_rbac', models.CharField(choices=[('admin', 'Administrador'), ('executive', 'Ejecutivo C-Suite'), ('division_manager', 'Director de División'), ('tech_manager', 'Gerente de Tecnología'), ('security_analyst', 'Analista de Seguridad'), ('finops_analyst', 'Analista FinOps'), ('pmo_manager', 'Gerente PMO'), ('hr_manager', 'Gerente de RRHH'), ('usuario', 'Usuario')], default='usuario', max_length=30)),
                ('division', models.CharField(choices=[('tech', 'Wayne Technologies'), ('industries', 'Wayne Industries'), ('healthcare', 'Wayne Healthcare'), ('realestate', 'Wayne Real Estate'), ('capital', 'Wayne Capital'), ('foundation', 'Wayne Foundation'), ('ventures', 'Wayne Ventures'), ('manor', 'Wayne Manor')], default='manor', max_length=30)),
                ('departamento', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('salario_anual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('permiso', 'En Permiso'), ('desvinculado', 'Desvinculado')], default='activo', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('full_time', 'Tiempo Completo'), ('part_time', 'Medio Tiempo'), ('contractor', 'Contratista'), ('temporal', 'Temporal')], default='full_time', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('formacion', models.CharField(blank=True, max_length=150)),
                ('anos_experiencia', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No especificado')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
