# Generated by Django 6.0.4 on 2026-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('station_id', models.CharField(blank=True, max_length=30)),
                ('station_name', models.CharField(blank=True, max_length=200)),
                ('gotham_district', models.CharField(blank=True, max_length=100)),
                ('station_type', models.CharField(blank=True, max_length=100)),
                ('energy_generated_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('energy_consumed_mwh', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('peak_demand_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('avg_demand_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('renewable_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('outage_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100)),
                ('grid_frequency_hz', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('transmission_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
