# Generated by Django 6.0.4 on 2026-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(max_length=30, unique=True)),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_type', models.CharField(max_length=50)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('project_category', models.CharField(blank=True, max_length=100)),
                ('gotham_district', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('tax_deductible', models.BooleanField(default=True)),
                ('matched', models.BooleanField(default=False)),
                ('recurring', models.BooleanField(default=False)),
                ('status', models.CharField(default='completed', max_length=50)),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
    ]
