# Generated by Django 6.0.4 on 2026-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TumblerTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=30, unique=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('vehicle_id', models.CharField(blank=True, max_length=30)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('mission_id', models.CharField(blank=True, max_length=30)),
                ('mission_type', models.CharField(blank=True, max_length=100)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_level_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('engine_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('battery_level_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gotham_zone', models.CharField(blank=True, max_length=100)),
                ('alert_type', models.CharField(blank=True, max_length=100)),
                ('system_status', models.CharField(default='operational', max_length=50)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
