# Generated by Django 6.0.3 on 2026-05-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('total_budget_musd', models.FloatField()),
                ('executed_cost_musd', models.FloatField()),
                ('physical_progress_pct', models.IntegerField()),
                ('financial_progress_pct', models.IntegerField()),
                ('security_incidents', models.IntegerField()),
                ('contractor', models.CharField(max_length=255)),
            ],
        ),
    ]
